import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-screen grid place-items-center text-4xl font-bold">
        <h2 className="text-purple-500 absolute text-6xl">Site under construction!</h2>

        <span className="absolute inline-block w-full h-full backdrop-blur-3xl" />

        <h1 className="flex gap-3 text-zinc-100">
          <span className="animate-bounce">Site</span>
          <span className="animate-bounce" style={{ animationDelay: '100ms' }}>under</span>
          <span className="animate-bounce" style={{ animationDelay: '200ms' }}>construction!</span>
        </h1>
      </main>
    </>
  );
}
